version: '3.8'

services:
  bootstrap:
    build:
      context: .
      dockerfile: bootstrap.Dockerfile
    ports:
      - "5003:5000"
    container_name: bootstrap

  node1:
    build: .
    environment:
      - PORT=5001
      - BOOTSTRAP=http://bootstrap:5000
    ports:
      - "5001:5000"
    depends_on:
      - bootstrap

  node2:
    build: .
    environment:
      - PORT=5002
      - BOOTSTRAP=http://bootstrap:5000
    ports:
      - "5002:5000"
    depends_on:
      - bootstrap

  node3:
    build: .
    environment:
      - PORT=5003
      - BOOTSTRAP=http://bootstrap:5000
    ports:
      - "5503:5000"
    depends_on:
      - bootstrap

  node4:
    build: .
    environment:
      - PORT=5004
      - BOOTSTRAP=http://bootstrap:5000
    ports:
      - "5004:5000"
    depends_on:
      - bootstrap

  node5:
    build: .
    environment:
      - PORT=5005
      - BOOTSTRAP=http://bootstrap:5000
    ports:
      - "5005:5000"
    depends_on:
      - bootstrap

  node6:
    build: .
    environment:
      - PORT=5006
      - BOOTSTRAP=http://bootstrap:5000
    ports:
      - "5006:5000"
    depends_on:
      - bootstrap

  node7:
    build: .
    environment:
      - PORT=5007
      - BOOTSTRAP=http://bootstrap:5000
    ports:
      - "5007:5000"
    depends_on:
      - bootstrap

  node8:
    build: .
    environment:
      - PORT=5008
      - BOOTSTRAP=http://bootstrap:5000
    ports:
      - "5008:5000"
    depends_on:
      - bootstrap

  node9:
    build: .
    environment:
      - PORT=5009
      - BOOTSTRAP=http://bootstrap:5000
    ports:
      - "5009:5000"
    depends_on:
      - bootstrap

  node10:
    build: .
    environment:
      - PORT=5010
      - BOOTSTRAP=http://bootstrap:5000
    ports:
      - "5010:5000"
    depends_on:
      - bootstrap

  node11:
    build: .
    environment:
      - PORT=5011
      - BOOTSTRAP=http://bootstrap:5000
    ports:
      - "5011:5000"
    depends_on:
      - bootstrap

  node12:
    build: .
    environment:
      - PORT=5012
      - BOOTSTRAP=http://bootstrap:5000
    ports:
      - "5012:5000"
    depends_on:
      - bootstrap
